// gradeMin/gradeMax и audienceSource описывают учебную адресацию, а не оформление.
// 'source' означает, что класс указан в исходнике; 'provisional' — предварительная редакторская оценка.
// При переносе уточнить provisional, заменить status на 'ready' и добавить load: () => import('./slug/Game.vue').
export const games = [
  { id: 'living-week', title: 'Живая неделя', topic: 'Дни недели · RU/KZ', interaction: 'Выбор ответа', source: 'zhivaya_nedelya_game_RU_KZ.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['weekdays'], format: ['choice'], language: ['ru-kz'] }, status: 'planned' },
  { id: 'build-week', title: 'Собери неделю', topic: 'Дни недели · RU/KZ', interaction: 'Сборка порядка', source: 'soberi_nedelyu_RU_KZ.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['weekdays'], format: ['sequence'], language: ['ru-kz'] }, status: 'planned' },
  { id: 'ali-day', title: 'День Али', topic: 'Время и распорядок дня · RU/KZ', interaction: 'Выбор и порядок', source: 'den_Ali_game_RU_KZ (1).html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['routine'], format: ['choice', 'sequence'], language: ['ru-kz'] }, status: 'planned' },
  { id: 'catch-number', title: 'Поймай число', topic: 'Числа 1–20 · RU/KZ', interaction: 'Память и выбор', source: 'poimai_chislo_1_20.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['numbers'], format: ['memory', 'choice'], language: ['ru-kz'] }, status: 'planned' },
  { id: 'text-types', title: 'Типы текста: осень', topic: '9 класс', interaction: 'Выбор и свободный текст', source: 'Trenazher_tipy_teksta_osen_9_klass.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['text-types'], format: ['choice', 'writing'], language: ['ru'] }, status: 'planned' },
  { id: 'complex-sentences', title: 'ССП, СПП и придаточные', topic: 'Синтаксис', interaction: 'Выбор с объяснением', source: 'trenazher_SSP_SPP_vidy_pridatochnyh.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'planned' },
  { id: 'union-or-word', title: 'Союз или союзное слово', topic: 'Синтаксис', interaction: 'Два шага', source: 'trenazher_soyuz_ili_soyuznoe_slovo.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'planned' },
  { id: 'union-or-word-extended', title: 'Союз или союзное слово: три тренировки', topic: 'Синтаксис', interaction: 'Выбор режима', source: 'trenazher_soyuz_ili_soyuznoe_slovo (1).html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'planned' },
  { id: 'subordinate-diagrams', title: 'Как подчиняются придаточные', topic: 'Синтаксис', interaction: 'Схемы и вкладки', source: 'Podchinenie_pridatochnyh_interaktivnaya_kartochka.html', gradeMin: null, gradeMax: null, audienceSource: 'unknown', defaultTheme: 'neutral', facets: { grade: ['unknown'], topic: ['syntax'], format: ['diagram'], language: ['ru'] }, status: 'planned' },
]
