// gradeMin/gradeMax и audienceSource описывают учебную адресацию, а не оформление.
// 'source' означает, что класс указан в исходнике; 'provisional' — предварительная редакторская оценка.
// При переносе уточнить provisional, заменить status на 'ready' и добавить load: () => import('./slug/Game.vue').
export const games = [
  { id: 'year-months', title: 'Круглый год: 12 месяцев', topic: 'Месяцы и времена года · 4 класс', interaction: 'Сборка года, сезоны и поиск слов', source: 'Сценарий согласован владельцем 8 октября 2026 года', gradeMin: 4, gradeMax: 4, audienceSource: 'source', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['months-seasons'], format: ['sequence', 'choice', 'word-search'], language: ['ru-kz'] }, status: 'ready', load: () => import('./year-months/Game.vue') },
  { id: 'one-member-sentences', title: 'Односоставные предложения', topic: 'Синтаксис · 9 класс', interaction: 'Выбор с объяснением', source: 'Trenazher_odnosostavnye_predlozheniya_9_klass.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./one-member-sentences/Game.vue') },
  { id: 'living-week', title: 'Живая неделя', topic: 'Дни недели · RU/KZ', interaction: 'Выбор ответа', source: 'zhivaya_nedelya_game_RU_KZ.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['weekdays'], format: ['choice'], language: ['ru-kz'] }, status: 'ready', load: () => import('./living-week/Game.vue') },
  { id: 'build-week', title: 'Собери неделю', topic: 'Дни недели · RU/KZ', interaction: 'Сборка порядка', source: 'soberi_nedelyu_RU_KZ.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['weekdays'], format: ['sequence'], language: ['ru-kz'] }, status: 'ready', load: () => import('./soberi-nedelyu/SoberiNedelyu.vue') },
  { id: 'ali-day', title: 'День Али', topic: 'Время и распорядок дня · RU/KZ', interaction: 'Выбор и порядок', source: 'den_Ali_game_RU_KZ (1).html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['routine'], format: ['choice', 'sequence'], language: ['ru-kz'] }, status: 'ready', load: () => import('./ali-day/Game.vue') },
  { id: 'catch-number', title: 'Поймай число', topic: 'Числа 1–20 · RU/KZ', interaction: 'Память и выбор', source: 'poimai_chislo_1_20.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['numbers'], format: ['memory', 'choice'], language: ['ru-kz'] }, status: 'ready', load: () => import('./catch-number/Game.vue') },
  { id: 'text-types', title: 'Типы текста: осень', topic: '9 класс', interaction: 'Выбор и свободный текст', source: 'Trenazher_tipy_teksta_osen_9_klass.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['text-types'], format: ['choice', 'writing'], language: ['ru-kz'] }, status: 'ready', load: () => import('./text-types/Game.vue') },
  { id: 'complex-sentences', title: 'ССП, СПП и придаточные', topic: 'Синтаксис', interaction: 'Выбор с объяснением', source: 'trenazher_SSP_SPP_vidy_pridatochnyh.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./complex-sentences/Game.vue') },
  { id: 'union-or-word', title: 'Союз или союзное слово', topic: 'Синтаксис', interaction: 'Два шага', source: 'trenazher_soyuz_ili_soyuznoe_slovo.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./union-or-word/Game.vue') },
  { id: 'union-or-word-extended', title: 'Союзы и запятые: шесть тренировок', topic: 'Синтаксис', interaction: 'Выбор и расстановка запятых', source: 'trenazher_soyuz_ili_soyuznoe_slovo (1).html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./union-or-word-extended/Game.vue') },
  { id: 'subordinate-diagrams', title: 'Как подчиняются придаточные', topic: 'Синтаксис', interaction: 'Схемы и вкладки', source: 'Podchinenie_pridatochnyh_interaktivnaya_kartochka.html', gradeMin: null, gradeMax: null, audienceSource: 'unknown', defaultTheme: 'neutral', facets: { grade: ['unknown'], topic: ['syntax'], format: ['diagram'], language: ['ru'] }, status: 'ready', load: () => import('./subordinate-diagrams/Game.vue') },
  { id: 'week-relative-days', title: 'Вчера, сегодня, завтра', topic: 'Дни недели · RU/KZ', interaction: 'Выбор дня и места', source: '01/dni_nedeli_vchera_segodnya_zavtra_sound.html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['weekdays'], format: ['choice'], language: ['ru-kz'] }, status: 'ready', load: () => import('./week-relative-days/Game.vue') },
  { id: 'literary-devices', title: 'Типы речи и художественные средства', topic: 'Осень · 9 класс', interaction: 'Выбор с объяснением', source: '02/Trenazher_hudozhestvennye_sredstva_osen_9_klass.html', gradeMin: 9, gradeMax: 9, audienceSource: 'source', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['text-types', 'literary-devices'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./literary-devices/Game.vue') },
  { id: 'ali-apples', title: 'Среда Али: покупки и рассказ', topic: 'Чтение и распорядок дня', interaction: 'Корзина и выбор ответа', source: '01/ali_sreda_click_basket_3_apples (1).html', gradeMin: 1, gradeMax: 4, audienceSource: 'provisional', defaultTheme: 'junior', facets: { grade: ['primary'], topic: ['routine'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./ali-apples/Game.vue') },
  { id: 'bsp', title: 'БСП: смысл подсказывает знак', topic: 'Бессоюзные сложные предложения · Подготовка к ЕНТ', interaction: 'Выбор знака, смысловой связи и цифр', source: 'trenazher_BSP.html', gradeMin: 9, gradeMax: 11, audienceSource: 'provisional', defaultTheme: 'senior', facets: { grade: ['senior'], topic: ['syntax'], format: ['choice'], language: ['ru'] }, status: 'ready', load: () => import('./bsp/Game.vue') },
]
